default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: rails-impromaq_development

test:
  <<: *default
  database: rails-impromaq_test

production:
  <<: *default
  database: rails-impromaq_production
  username: rails-impromaq
  password: <%= ENV['RAILS-IMPROMAQ_DATABASE_PASSWORD'] %>
